# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-07 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catNumber', models.IntegerField(blank=True, default=0, null=True)),
                ('accNum', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('site', models.CharField(blank=True, max_length=120, null=True)),
                ('siteNumber', models.CharField(blank=True, max_length=120, null=True)),
                ('locality', models.TextField(blank=True, null=True)),
                ('situation', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('fileName', models.CharField(blank=True, max_length=120, null=True)),
                ('uid', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['accNum', 'catNumber'],
            },
        ),
    ]
