# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('siteNumber', models.CharField(blank=True, max_length=120, null=True)),
                ('locality', models.TextField(blank=True, null=True)),
                ('site', models.CharField(blank=True, max_length=120, null=True)),
                ('fileName', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('situation', models.TextField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('accNum', models.CharField(blank=True, default=uuid.uuid4, max_length=10, unique=True)),
            ],
        ),
    ]
